import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useData } from '@/hooks/useData';

import { User } from '@/data/mockData';

type Language = 'uz' | 'ru' | 'en';
type Theme = 'light' | 'dark';
type ColorTheme = 'default' | 'ocean' | 'sunset' | 'forest' | 'berry';

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  colorTheme: ColorTheme;
  setColorTheme: (theme: ColorTheme) => void;
  user: User | null;
  setUser: (user: User | null) => void;
  isAuthenticated: boolean;
  login: (email: string, password: string) => Promise<boolean>;
  logout: () => void;
  t: (key: string) => string;
  currentBranch: string;
  setCurrentBranch: (branchId: string) => void;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    'years_old': 'yosh',
    'status_active': 'Faol',
    'status_inactive': 'Nofaol',
    'inactive': 'Nofaol',
    'login': 'Kirish',
    'logout': 'Chiqish',
    'email': 'Elektron pochta',
    'password': 'Parol',
    'login_title': 'Tizimga kirish',
    'login_subtitle': "Bog'cha boshqaruv tizimiga xush kelibsiz",
    'invalid_credentials': "Noto'g'ri login yoki parol",
    'dashboard': 'Boshqaruv paneli',
    'branch': 'Filial',
    'branches': 'Filiallar',
    'groups': 'Guruhlar',
    'students': "O'quvchilar",
    'teacher': "O'qituvchi",
    'teachers': "O'qituvchilar",
    'parent': 'Ota-ona',
    'parents': 'Ota-onalar',
    'staff': 'Xodimlar',
    'meals': 'Ovqatlanish',
    'vaccination': 'Emlash',
    'activities': "Mashg'ulotlar",
    'warehouse': 'Ombor',
    'finance': 'Moliya',
    'reports': 'Hisobotlar',
    'settings': 'Sozlamalar',
    'users': 'Foydalanuvchilar',
    'sleep': 'Uxlash',
    'homework': 'Uy vazifasi',
    'admission': 'Qabul',
    'complaints': 'Shikoyatlar',
    'qr_code': 'QR Kod',
    'total_students': 'Jami bolalar',
    'total_groups': 'Jami guruhlar',
    'total_revenue': 'Jami tushum',
    'total_staff': 'Jami xodimlar',
    'financial_report': 'Moliyaviy hisobot',
    'revenue': 'Tushum',
    'expenses': 'Xarajat',
    'profit': 'Foyda',
    'branch_statistics': 'Filial statistikasi',
    'this_month': 'Bu oy',
    'last_month': "O'tgan oy",
    'attendance_today': 'Bugungi davomad',
    'add_branch': "Filial qo'shish",
    'edit_branch': 'Filialni tahrirlash',
    'branch_name': 'Filial nomi',
    'capacity': "Sig'im",
    'phone': 'Telefon',
    'address': 'Manzil',
    'location': 'Joylashuv',
    'select_location': 'Xaritadan joy tanlang',
    'students_count': "O'quvchilar soni",
    'groups_count': 'Guruhlar soni',
    'search': 'Qidirish',
    'filter_by_group': "Guruh bo'yicha saralash",
    'all_branches': 'Barcha filiallar',
    'save': 'Saqlash',
    'cancel': 'Bekor qilish',
    'delete': "O'chirish",
    'edit': 'Tahrirlash',
    'actions': 'Amallar',
    'loading': 'Yuklanmoqda...',
    'no_data': "Ma'lumot yo'q",
    'success': 'Muvaffaqiyatli',
    'error': 'Xatolik',
    'confirm': 'Tasdiqlash',
    'total': 'Jami',
    'welcome': 'Xush kelibsiz',
    'good_morning': 'Xayrli tong',
    'good_afternoon': 'Xayrli kun',
    'good_evening': 'Xayrli kech',
    'language': 'Til',
    'theme': 'Mavzu',
    'color_theme': 'Rang mavzusi',
    'dark_mode': "Qorong'u rejim",
    'light_mode': "Yorug' rejim",
    'notifications': 'Bildirishnomalar',
    'mark_all_read': "Barchasini o'qilgan deb belgilash",
    'no_notifications': "Bildirishnomalar yo'q",
    'my_child_attendance': "Farzandim davomadi",
    'my_child': "Farzandim",
    'status_completed': 'Bajarilgan',
    'status_scheduled': 'Rejalashtirilgan',
    'status_overdue': 'Kechiktirilgan',
    'fill_all_fields': "Barcha maydonlarni to'ldiring",
    'vaccination_added': "Emlash qo'shildi",
    'access_denied': 'Kirish taqiqlangan',
    'teacher_no_access': "O'qituvchilar ushbu sahifaga kira olmaydi",
    'my_child_vaccination': 'Farzandim emlash vaqtlari',
    'add_vaccination': "Emlash qo'shish",
    'vaccination_list': "Emlash ro'yxati",
    'next_dose': 'Keyingi doza',
    'new_vaccination': 'Yangi emlash',
    'student': "O'quvchi",
    'vaccine_name': 'Emlash nomi',
    'date': 'Sana',
    'next_dose_date': 'Keyingi doza sanasi',
    'status': 'Holat',
    'select': 'Tanlang',
    'homework_added': "Uy vazifasi qo'shildi",
    'my_child_homework': 'Farzandim uy vazifalari',
    'add_homework': "Vazifa qo'shish",
    'active_tasks': 'Faol vazifalar',
    'completed_tasks': 'Bajarilgan vazifalar',
    'due_date': 'Muddat',
    'new_homework': 'Yangi uy vazifasi',
    'group': 'Guruh',
    'title': 'Sarlavha',
    'description': 'Tavsif',
    'sleep_record_added': "Uyqu yozuvi qo'shildi",
    'my_child_sleep': 'Farzandim uyqusi',
    'add_record': "Yozuv qo'shish",
    'recorded_today': 'Bugun yozilgan',
    'good_sleep': 'Yaxshi uyqu',
    'good_sleep_percentage': 'Yaxshi uyqu %',
    'sleep_records': 'Uyqu yozuvlari',
    'new_sleep_record': 'Yangi uyqu yozuvi',
    'start_time': 'Boshlanish vaqti',
    'end_time': 'Tugash vaqti',
    'quality': 'Sifati',
    'good': 'Yaxshi',
    'fair': "O'rtacha",
    'poor': 'Yomon',
    'activity_added': "Mashg'ulot qo'shildi",
    'my_child_activities': "Farzandim mashg'ulotlari",
    'add_activity': "Mashg'ulot qo'shish",
    'no_activities_found': "Mashg'ulotlar topilmadi",
    'new_activity': "Yangi mashg'ulot",
    'activity_name': "Mashg'ulot nomi",
    'type': 'Turi',
    'time': 'Vaqt',
    'duration': 'Davomiyligi',
    'minutes': 'daqiqa',
    'hours': 'soat',
    'active': 'Faol',
    'completed': 'Bajarilgan',
    'overdue': "Muddati o'tgan",
    'leave_empty': "O'zgartirish uchun kiriting",
    'upload_photo': "Rasm yuklash",
    'change_photo': "Rasmni o'zgartirish",
    'remove_photo': "Rasmni o'chirish",
    'add_group': "Guruh qo'shish",
    'new_complaint': "Yangi shikoyat",
    'subject': "Mavzu",
    'subject_placeholder': "Shikoyat mavzusi...",
    'description_placeholder': "Shikoyat mazmuni...",
    'send': "Yuborish",
    'super_dashboard': "Super Boshqaruv",
    'crm_management': "Mijozlar Boshqaruvi",
    'add_student': "O'quvchi qo'shish",
    'add_teacher': "O'qituvchi qo'shish",
    'add_parent': "Ota-ona qo'shish",
    'add_meal': "Taom qo'shish",
    'add_complaint': "Shikoyat qo'shish",
    'edit_student': "O'quvchini tahrirlash",
    'edit_group': 'Guruhni tahrirlash',
    'edit_teacher': "O'qituvchini tahrirlash",
    'edit_parent': 'Ota-onani tahrirlash',
    'today_menu': 'Bugungi taomnoma',
    'add_menu': "Taomnoma qo'shish",
    'meal_breakfast': 'Nonushta',
    'meal_lunch': 'Tushlik',
    'meal_snack': 'Ikkinchi tushlik',
    'meal_dinner': 'Kechki ovqat',
    'meal_not_set': 'Taomnoma kiritilmagan',
    'no_menu_set': 'Bugun uchun taomnoma belgilanmagan',
    'menu_history': 'Taomnoma tarixi',
    'complaints_subtitle': "Shikoyat va takliflarni boshqarish",
    'send_complaint': "Shikoyat yuborish",
    'status_pending': 'Kutilmoqda',
    'status_resolved': 'Hal etilgan',
    'complaints_list': "Shikoyatlar ro'yxati",
    'complaint_title': 'Shikoyat mavzusi',
    'complaint_description': 'Shikoyat matni',
    'reply': "Javob berish",
    'response_placeholder': "Javobingizni yozing...",
    'complaint_sent': "Murojaat yuborildi",
    'response_sent': "Javob yuborildi",
    'response': "Javob",
    'student_info': "O'quvchi ma'lumotlari",
    'full_name': "F.I.Sh",
    'age': "Yoshi",
    'parent_info': "Ota-ona ma'lumotlari",
    'parent_name': "Ota-ona F.I.Sh",
    'birth_date': "Tug'ilgan sana",
    'photo_url': "Rasm URL",
    'specialization': "Mutaxassislik",
    'assigned_groups': "Biriktirilgan guruhlar",
    'group_name': "Guruh nomi",
    'age_range': "Yosh oralig'i",
    'children': "Farzandlar",
    'child_count': "Farzand soni",
    'teachers_subtitle': "O'qituvchilar va ularning guruhlari",
    'email_exists': "Bu email band",
    'password_min_length': "Parol kamida 4 belgi",
    'fill_required_fields': "Majburiy maydonlarni to'ldiring",
    'select_branch_first': "Avval filialni tanlang",
    'no_groups_in_branch': "Bu filialda guruhlar yo'q",
    'parent_not_found': "Ota-ona topilmadi",
    'delete_confirmation': "Haqiqatan ham o'chirmoqchimisiz?",
    'create': "Yaratish",
    'student_parent_created': "O'quvchi va ota-ona yaratildi",
    'fill_parent_info': "Ota-ona ma'lumotlarini to'ldiring",
    'new_group': "Yangi guruh",
    'group_updated': "Guruh yangilandi",
    'group_deleted': "Guruh o'chirildi",
    'group_added': "Guruh qo'shildi",
    'student_updated': "O'quvchi yangilandi",
    'student_deleted': "O'quvchi o'chirildi",
    'teacher_updated': "O'qituvchi yangilandi",
    'teacher_deleted': "O'qituvchi o'chirildi",
    'parent_updated': "Ota-ona yangilandi",
    'parent_deleted': "Ota-ona o'chirildi",
    'parent_added': "Ota-ona qo'shildi",
    'teacher_created': "O'qituvchi yaratildi",
    'all_groups': "Barcha guruhlar",
    'email_login': "Email (Login)",
    'add_student_parent': "Yangi o'quvchi va Ota-ona",
    'financial_records': 'Moliyaviy hisobotlar',
    'annual_stats': "Yillik ko'rsatkichlar",
    'recent_transactions': "So'nggi amaliyotlar",
    'financial_record': "Moliyaviy yozuv",
    'amount': "Miqdor",
    'amount_sum': "Miqdor (so'm)",
    'category': "Kategoriya",
    'income_added': "Tushum qo'shildi",
    'expense_added': "Xarajat qo'shildi",
    'add_product': "Mahsulot qo'shish",
    'product_name': "Mahsulot nomi",
    'quantity': "Miqdor",
    'unit': "Birlik",
    'min_stock': "Min. zaxira",
    'total_products': "Jami mahsulotlar",
    'categories': "Kategoriyalar",
    'low_stock': "Kam qolgan",
    'low_stock_items': "Kam qolgan mahsulotlar",
    'product_added': "Mahsulot qo'shildi",
    'record_updated': "Yozuv yangilandi",
    'record_deleted': "Yozuv o'chirildi",
    'edit_record': "Yozuvni tahrirlash",
    'delete_record': "Yozuvni o'chirish",
    'new_product': "Yangi mahsulot",
    'updated': "Yangilangan",
    'warehouse_management': "Ombor boshqaruvi",
    'no_active_tasks': "Faol vazifalar yo'q",
    'branch_not_found': "Filial topilmadi",
    'branch_added': "Yangi filial qo'shildi",
    'branch_updated': "Filial yangilandi",
    'branch_deleted': "Filial o'chirildi",
    'admission_applications': "Qabul arizalari",
    'add_application': "Ariza qo'shish",
    'pending': "Kutilmoqda",
    'approved': "Tasdiqlangan",
    'rejected': "Rad etilgan",
    'waitlist': "Kutish ro'yxati",
    'total_applications': "Jami arizalar",
    'applications_list': "Arizalar ro'yxati",

    'preferred_branch': "Afzal filial",
    'application_added': "Ariza qo'shildi",
    'status_updated': "Holat yangilandi",
    'approve': "Tasdiqlash",
    'reject': "Rad etish",
    'activities_schedule': "Mashg'ulotlar jadvali",
    'educational': "Ta'limiy",
    'physical': "Jismoniy",
    'creative': "Ijodiy",
    'social': "Ijtimoiy",
    'child_name': "Bola ismi",

    'duration_min': "Davomiyligi (daqiqa)",
    'about_activity': "Mashg'ulot haqida...",
    'sleep_monitoring': "Bolalar uyqusi monitoringi",
    'new_menu': "Yangi taomnoma",
    'menu_name': "Taomnoma nomi",
    'meal_type': "Taom vaqti",
    'calories': "Kaloriya",
    'menu_items': "Menyu tarkibi",
    'my_groups': "Mening guruhlarim",

    'my_children': "Farzandlarim",

    // Settings & Themes
    'theme_default': 'Standart',
    'theme_default_desc': "Klassik ko'k va binafsha",
    'theme_ocean': 'Okean',
    'theme_ocean_desc': 'Tinch va tetiklantiruvchi',
    'theme_sunset': 'Quyosh botishi',
    'theme_sunset_desc': 'Issiq va jonli',
    'theme_forest': "O'rmon",
    'theme_forest_desc': 'Tabiiy va yangi',
    'theme_berry': 'Reza meva',
    'theme_berry_desc': "Boy va o'ynoqi",

    'settings_subtitle': "Tizim sozlamalarini boshqarish",
    'select_language': "Tizim tilini tanlang",
    'select_theme_mode': "Yorug' yoki qorong'u rejim",
    'select_color_theme': "Ranglar sxemasini tanlang",
    'preview_appearance': "Ko'rinish namunasi",
    'danger_zone': "Xavfli hudud",
    'manage_system_data': "Tizim ma'lumotlarini boshqarish",
    'reset_system': "Tizimni tozalash",
    'reset_system_desc': "Barcha kiritilgan ma'lumotlar o'chib ketadi va tizim dastlabki holatga qaytadi.",
    'clear_data': "Ma'lumotlarni tozalash",
    'confirm_reset': "Haqiqatan ham barcha ma'lumotlarni o'chirmoqchimisiz? Bu amalni ortga qaytarib bo'lmaydi.",
    'system_reset_success': "Tizim tozalandi",
    'button_primary': 'Asosiy',
    'button_secondary': 'Ikkilamchi',
    'button_success': 'Muvaffaqiyat',
    'button_warning': 'Ogohlantirish',

    // QR Code
    'qr_code_subtitle': "QR kod skanerlash va davomad",
    'scan_simulator': "Skaner simulyatori",
    'click_to_simulate': "Davomadni qayd etish uchun quyidagi tugmalarni bosing",
    'check_in': 'Kirish',
    'check_out': 'Chiqish',
    'attendance_history': 'Davomad tarixi',
    'scanned_in': 'Kirdi',
    'scanned_out': 'Chiqdi',
    'arrived': 'Kelganlar',
    'left': 'Ketganlar',
    'select_student_qr': "O'quvchini tanlang",
    'download': 'Yuklab olish',
    'refresh': 'Yangilash',
    'check_in_success': 'Kirish qayd etildi',
    'check_out_success': 'Chiqish qayd etildi',
    'select_student_error': "Avval o'quvchini tanlang",

    // Dashboard
    'dashboard_subtitle': "Bog'cha faoliyati haqida umumiy ma'lumot",

    // Users
    'users_subtitle': "Tizim foydalanuvchilari",
    'add_user': "Foydalanuvchi qo'shish",
    'edit_user': "Foydalanuvchini tahrirlash",
    'new_user': "Yangi foydalanuvchi",
    'filter_all': "Barchasi",
    'filter_directors': "Direktorlar",
    'filter_admins': "Adminlar",
    'filter_teachers': "O'qituvchilar",
    'filter_parents': "Ota-onalar",
    'role_director': "Direktor",
    'role_admin': "Admin",
    'role_teacher': "O'qituvchi",
    'role_parent': "Ota-ona",
    'role_superadmin': "Super Admin",
    'fill_all_fields_error': "Barcha maydonlarni to'ldiring",
    'branch_required_error': "Xodim uchun filial tanlanishi shart (Required)",
    'user_updated': "Foydalanuvchi yangilandi",
    'user_added': "Yangi foydalanuvchi qo'shildi",
    'user_deleted': "Foydalanuvchi o'chirildi",
    'delete_user_confirm': "Bu foydalanuvchini o'chirmoqchimisiz?",
    'no_permission': "Ruxsat yo'q",
    'no_permission_desc': "Bu sahifaga kirish huquqingiz yo'q",
    'full_name_label': "To'liq ism",
    'new_password_placeholder': "Yangi parol (o'zgartirish uchun)",
    'role': "Rol",
    'status_label': "Holat",
    'branch_select_hint': "Agar filial tanlansa, foydalanuvchi faqat shu filial ma'lumotlarini ko'radi.",
    'no_users_found': "Bu bo'limda foydalanuvchilar topilmadi",
  },
  ru: {
    'years_old': 'лет',
    'status_active': 'Активный',
    'status_inactive': 'Неактивный',
    'inactive': 'Неактивный',
    'login': 'Вход',
    'logout': 'Выход',
    'email': 'Электронная почта',
    'password': 'Пароль',
    'login_title': 'Вход в систему',
    'login_subtitle': 'Добро пожаловать в систему управления детским садом',
    'invalid_credentials': 'Неверный логин или пароль',
    'dashboard': 'Панель управления',
    'branch': 'Филиал',
    'branches': 'Филиалы',
    'groups': 'Группы',
    'students': 'Ученики',
    'teacher': 'Учитель',
    'teachers': 'Учителя',
    'parent': 'Родитель',
    'parents': 'Родители',
    'staff': 'Сотрудники',
    'meals': 'Питание',
    'vaccination': 'Вакцинация',
    'activities': 'Занятия',
    'warehouse': 'Склад',
    'finance': 'Финансы',
    'reports': 'Отчеты',
    'settings': 'Настройки',
    'users': 'Пользователи',
    'sleep': 'Сон',
    'homework': 'Домашнее задание',
    'admission': 'Приём',
    'complaints': 'Жалобы',
    'qr_code': 'QR Код',
    'total_students': 'Всего детей',
    'total_groups': 'Всего групп',
    'total_revenue': 'Общий доход',
    'total_staff': 'Всего сотрудников',
    'financial_report': 'Финансовый отчет',
    'revenue': 'Доход',
    'expenses': 'Расходы',
    'profit': 'Прибыль',
    'branch_statistics': 'Статистика филиалов',
    'this_month': 'Этот месяц',
    'last_month': 'Прошлый месяц',
    'attendance_today': 'Посещаемость сегодня',
    'add_branch': 'Добавить филиал',
    'edit_branch': 'Редактировать филиал',
    'branch_name': 'Название филиала',
    'capacity': 'Вместимость',
    'phone': 'Телефон',
    'address': 'Адрес',
    'location': 'Расположение',
    'select_location': 'Выберите место на карте',
    'students_count': 'Количество учеников',
    'groups_count': 'Количество групп',
    'search': 'Поиск',
    'filter_by_group': 'Фильтр по группе',
    'all_branches': 'Все филиалы',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Редактировать',
    'actions': 'Действия',
    'loading': 'Загрузка...',
    'no_data': 'Нет данных',
    'success': 'Успешно',
    'error': 'Ошибка',
    'confirm': 'Подтвердить',
    'total': 'Всего',
    'welcome': 'Добро пожаловать',
    'good_morning': 'Доброе утро',
    'good_afternoon': 'Добрый день',
    'good_evening': 'Добрый вечер',
    'language': 'Язык',
    'theme': 'Тема',
    'color_theme': 'Цветовая тема',
    'dark_mode': 'Тёмный режим',
    'light_mode': 'Светлый режим',
    'notifications': 'Уведомления',
    'mark_all_read': 'Пометить все как прочитанные',
    'no_notifications': 'Нет уведомлений',
    'my_child_attendance': 'Посещаемость моего ребенка',
    'my_child': 'Мой ребенок',
    'status_completed': 'Завершено',
    'status_scheduled': 'Запланировано',
    'status_overdue': 'Просрочено',
    'fill_all_fields': 'Заполните все поля',
    'vaccination_added': 'Вакцинация добавлена',
    'access_denied': 'Доступ запрещен',
    'teacher_no_access': 'Учителя не имеют доступа к этой странице',
    'my_child_vaccination': 'Вакцинация моего ребенка',
    'add_vaccination': 'Добавить вакцинацию',
    'vaccination_list': 'Список вакцинаций',
    'next_dose': 'Следующая доза',
    'new_vaccination': 'Новая вакцинация',
    'student': 'Ученик',
    'vaccine_name': 'Название вакцины',
    'date': 'Дата',
    'next_dose_date': 'Дата следующей дозы',
    'status': 'Статус',
    'select': 'Выберите',
    'homework_added': 'Домашнее задание добавлено',
    'my_child_homework': 'Домашнее задание моего ребенка',
    'add_homework': 'Добавить задание',
    'active_tasks': 'Активные задания',
    'completed_tasks': 'Завершенные задания',
    'due_date': 'Срок сдачи',
    'new_homework': 'Новое домашнее задание',
    'group': 'Группа',
    'title': 'Заголовок',
    'description': 'Описание',
    'sleep_record_added': 'Запись о сне добавлена',
    'my_child_sleep': 'Сон моего ребенка',
    'add_record': 'Добавить запись',
    'recorded_today': 'Записано сегодня',
    'good_sleep': 'Хороший сон',
    'good_sleep_percentage': '% хорошего сна',
    'sleep_records': 'Записи сна',
    'new_sleep_record': 'Новая запись сна',
    'start_time': 'Время начала',
    'end_time': 'Время окончания',
    'quality': 'Качество',
    'good': 'Хорошо',
    'fair': 'Средне',
    'poor': 'Плохо',
    'activity_added': 'Занятие добавлено',
    'my_child_activities': 'Занятия моего ребенка',
    'add_activity': 'Добавить занятие',
    'no_activities_found': 'Занятия не найдены',
    'new_activity': 'Новое занятие',
    'activity_name': 'Название занятия',
    'type': 'Тип',
    'time': 'Время',
    'duration': 'Длительность',
    'minutes': 'минут',
    'hours': 'часов',
    'active': 'Активный',
    'completed': 'Завершено',
    'overdue': 'Просрочено',
    'leave_empty': 'Оставьте пустым, если не меняете',
    'upload_photo': 'Загрузить фото',
    'change_photo': 'Изменить фото',
    'remove_photo': 'Удалить фото',
    'add_group': 'Добавить группу',
    'new_complaint': 'Новая жалоба',
    'subject': 'Тема',
    'subject_placeholder': 'Тема жалобы...',
    'description_placeholder': 'Содержание жалобы...',
    'send': 'Отправить',
    'super_dashboard': 'Супер Админ',
    'crm_management': 'Управление Клиентами',
    'add_student': 'Добавить ученика',
    'add_teacher': 'Добавить учителя',
    'add_parent': 'Добавить родителя',
    'add_meal': 'Добавить блюдо',
    'add_complaint': 'Добавить жалобу',
    'edit_student': 'Редактировать ученика',
    'edit_group': 'Редактировать группу',
    'edit_teacher': 'Редактировать учителя',
    'edit_parent': 'Редактировать родителя',
    'today_menu': 'Меню на сегодня',
    'add_menu': 'Добавить меню',
    'meal_breakfast': 'Завтрак',
    'meal_lunch': 'Обед',
    'meal_snack': 'Полдник',
    'meal_dinner': 'Ужин',
    'meal_not_set': 'Меню не задано',
    'no_menu_set': 'Меню на сегодня не установлено',
    'menu_history': 'История меню',
    'complaints_subtitle': 'Управление жалобами и предложениями',
    'send_complaint': 'Отправить жалобу',
    'status_pending': 'В ожидании',
    'status_resolved': 'Решено',
    'complaints_list': 'Список жалоб',
    'complaint_title': 'Тема жалобы',
    'complaint_description': 'Текст жалобы',
    'reply': "Ответить",
    'response_placeholder': "Напишите ваш ответ...",
    'complaint_sent': "Жалоба отправлена",
    'response_sent': "Ответ отправлен",
    'response': "Ответ",
    'student_info': "Информация об ученике",
    'full_name': "Ф.И.О.",
    'age': "Возраст",
    'parent_info': "Информация о родителях",
    'parent_name': "Ф.И.О. родителя",
    'birth_date': "Дата рождения",
    'photo_url': "URL фото",
    'specialization': "Специализация",
    'assigned_groups': "Прикрепленные группы",
    'group_name': "Название группы",
    'age_range': "Возрастной диапазон",
    'children': "Дети",
    'child_count': "Количество детей",
    'teachers_subtitle': "Учителя и их группы",
    'email_exists': "Этот email уже занят",
    'password_min_length': "Пароль минимум 4 символа",
    'fill_required_fields': "Заполните обязательные поля",
    'select_branch_first': "Сначала выберите филиал",
    'no_groups_in_branch': "В этом филиале нет групп",
    'parent_not_found': "Родитель не найден",
    'delete_confirmation': "Вы действительно хотите удалить?",
    'create': "Создать",
    'student_parent_created': "Ученик и родитель созданы",
    'fill_parent_info': "Заполните информацию о родителе",
    'new_group': "Новая группа",
    'group_updated': "Группа обновлена",
    'group_deleted': "Группа удалена",
    'group_added': "Группа добавлена",
    'student_updated': "Ученик обновлен",
    'student_deleted': "Ученик удален",
    'teacher_updated': "Учитель обновлен",
    'teacher_deleted': "Учитель удален",
    'parent_updated': "Родитель обновлен",
    'parent_deleted': "Родитель удален",
    'parent_added': "Родитель добавлен",
    'teacher_created': "Учитель создан",
    'all_groups': "Все группы",
    'email_login': "Email (Логин)",
    'add_student_parent': "Новый ученик и родитель",
    'financial_records': 'Финансовые отчеты',
    'annual_stats': "Годовые показатели",
    'recent_transactions': "Последние операции",
    'financial_record': "Финансовая запись",
    'amount': "Сумма",
    'amount_sum': "Сумма (сум)",
    'category': "Категория",
    'income_added': "Доход добавлен",
    'expense_added': "Расход добавлен",
    'product_name': "Название продукта",
    'quantity': "Количество",
    'unit': "Единица",
    'min_stock': "Мин. запас",
    'total_products': "Всего продуктов",
    'categories': "Категории",
    'low_stock': "Мало на складе",
    'low_stock_items': "Товары с низким запасом",
    'product_added': "Продукт добавлен",
    'add_product': "Добавить продукт",
    'record_updated': "Запись обновлена",
    'record_deleted': "Запись удалена",
    'edit_record': "Редактировать запись",
    'delete_record': "Удалить запись",
    'new_product': "Новый продукт",
    'updated': "Обновлено",
    'warehouse_management': "Управление складом",
    'no_active_tasks': "Нет активных задач",
    'branch_not_found': "Филиал не найден",
    'branch_added': "Новый филиал добавлен",
    'branch_updated': "Филиал обновлен",
    'branch_deleted': "Филиал удален",
    'admission_applications': "Заявки на прием",
    'add_application': "Добавить заявку",
    'pending': "Ожидает",
    'approved': "Одобрено",
    'rejected': "Отклонено",
    'waitlist': "Лист ожидания",
    'total_applications': "Всего заявок",
    'applications_list': "Список заявок",

    'preferred_branch': "Предпочтительный филиал",
    'application_added': "Заявка добавлена",
    'status_updated': "Статус обновлен",
    'approve': "Одобрить",
    'reject': "Отклонить",
    'activities_schedule': "Расписание занятий",
    'educational': "Образовательный",
    'physical': "Физический",
    'creative': "Творческий",
    'social': "Социальный",
    'child_name': "Имя ребенка",

    'duration_min': "Продолжительность (мин)",
    'about_activity': "О занятии...",
    'sleep_monitoring': "Мониторинг сна",
    'new_menu': "Новое меню",
    'menu_name': "Название меню",
    'meal_type': "Время приема пищи",
    'calories': "Калории",
    'menu_items': "Состав меню",
    'my_groups': "Мои группы",
    'my_children': "Мои дети",

    // Settings & Themes
    'theme_default': 'Стандартный',
    'theme_default_desc': 'Классический синий и фиолетовый',
    'theme_ocean': 'Океан',
    'theme_ocean_desc': 'Спокойный и освежающий',
    'theme_sunset': 'Закат',
    'theme_sunset_desc': 'Теплый и яркий',
    'theme_forest': 'Лес',
    'theme_forest_desc': 'Естественный и свежий',
    'theme_berry': 'Ягода',
    'theme_berry_desc': 'Насыщенный и игривый',

    'settings_subtitle': 'Управление настройками системы',
    'select_language': 'Выберите язык системы',
    'select_theme_mode': 'Светлый или темный режим',
    'select_color_theme': 'Выберите цветовую схему',
    'preview_appearance': 'Пример внешнего вида',
    'danger_zone': 'Опасная зона',
    'manage_system_data': 'Управление системными данными',
    'reset_system': 'Сброс системы',
    'reset_system_desc': 'Все введенные данные будут удалены, и система вернется в исходное состояние.',
    'clear_data': 'Очистить данные',
    'confirm_reset': 'Вы действительно хотите удалить все данные? Это действие нельзя отменить.',
    'system_reset_success': 'Система сброшена',
    'button_primary': 'Основная',
    'button_secondary': 'Вторичная',
    'button_success': 'Успех',
    'button_warning': 'Предупреждение',

    // QR Code
    'qr_code_subtitle': 'Сканирование QR-кода и посещаемость',
    'scan_simulator': 'Симулятор сканера',
    'click_to_simulate': 'Нажмите кнопки ниже, чтобы записать посещаемость',
    'check_in': 'Вход',
    'check_out': 'Выход',
    'attendance_history': 'История посещаемости',
    'scanned_in': 'Вошел',
    'scanned_out': 'Вышел',
    'arrived': 'Пришли',
    'left': 'Ушли',
    'select_student_qr': 'Выберите ученика',
    'download': 'Скачать',
    'refresh': 'Обновить',
    'check_in_success': 'Вход зарегистрирован',
    'check_out_success': 'Выход зарегистрирован',
    'select_student_error': 'Сначала выберите ученика',

    // Dashboard
    'dashboard_subtitle': 'Общая информация о деятельности детского сада',

    // Users
    'users_subtitle': 'Пользователи системы',
    'add_user': 'Добавить пользователя',
    'edit_user': 'Редактировать пользователя',
    'new_user': 'Новый пользователь',
    'filter_all': 'Все',
    'filter_directors': 'Директора',
    'filter_admins': 'Администраторы',
    'filter_teachers': 'Учителя',
    'filter_parents': 'Родители',
    'role_director': 'Директор',
    'role_admin': 'Администратор',
    'role_teacher': 'Учитель',
    'role_parent': 'Родитель',
    'role_superadmin': 'Супер Админ',
    'fill_all_fields_error': 'Заполните все поля',
    'branch_required_error': 'Для сотрудника выбор филиала обязателен',
    'user_updated': 'Пользователь обновлен',
    'user_added': 'Новый пользователь добавлен',
    'user_deleted': 'Пользователь удален',
    'delete_user_confirm': 'Вы действительно хотите удалить этого пользователя?',
    'no_permission': 'Нет доступа',
    'no_permission_desc': 'У вас нет прав для просмотра этой страницы',
    'full_name_label': 'Полное имя',
    'new_password_placeholder': 'Новый пароль (для изменения)',
    'role': 'Роль',
    'status_label': 'Статус',
    'branch_select_hint': 'Если выбран филиал, пользователь будет видеть данные только этого филиала.',
    'no_users_found': 'Пользователи в этом разделе не найдены',
  },
  en: {
    'years_old': 'years old',
    'status_active': 'Active',
    'status_inactive': 'Inactive',
    'inactive': 'Inactive',
    'login': 'Login',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'login_title': 'Sign In',
    'login_subtitle': 'Welcome to Kindergarten Management System',
    'invalid_credentials': 'Invalid email or password',
    'dashboard': 'Dashboard',
    'branch': 'Branch',
    'branches': 'Branches',
    'groups': 'Groups',
    'students': 'Students',
    'teacher': 'Teacher',
    'teachers': 'Teachers',
    'parent': 'Parent',
    'parents': 'Parents',
    'staff': 'Staff',
    'meals': 'Meals',
    'vaccination': 'Vaccination',
    'activities': 'Activities',
    'warehouse': 'Warehouse',
    'finance': 'Finance',
    'reports': 'Reports',
    'settings': 'Settings',
    'users': 'Users',
    'sleep': 'Sleep Tracking',
    'homework': 'Homework',
    'admission': 'Admission',
    'complaints': 'Complaints',
    'qr_code': 'QR Code',
    'total_students': 'Total Students',
    'total_groups': 'Total Groups',
    'total_revenue': 'Total Revenue',
    'total_staff': 'Total Staff',
    'financial_report': 'Financial Report',
    'revenue': 'Revenue',
    'expenses': 'Expenses',
    'profit': 'Profit',
    'branch_statistics': 'Branch Statistics',
    'this_month': 'This Month',
    'last_month': 'Last Month',
    'attendance_today': 'Attendance Today',
    'add_branch': 'Add Branch',
    'edit_branch': 'Edit Branch',
    'branch_name': 'Branch Name',
    'capacity': 'Capacity',
    'phone': 'Phone',
    'address': 'Address',
    'location': 'Location',
    'select_location': 'Select location on map',
    'students_count': 'Students Count',
    'groups_count': 'Groups Count',
    'search': 'Search',
    'filter_by_group': 'Filter by Group',
    'all_branches': 'All Branches',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'actions': 'Actions',
    'loading': 'Loading...',
    'no_data': 'No data available',
    'success': 'Success',
    'error': 'Error',
    'confirm': 'Confirm',
    'total': 'Total',
    'welcome': 'Welcome',
    'good_morning': 'Good Morning',
    'good_afternoon': 'Good Afternoon',
    'good_evening': 'Good Evening',
    'language': 'Language',
    'theme': 'Theme',
    'color_theme': 'Color Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'notifications': 'Notifications',
    'mark_all_read': 'Mark all as read',
    'no_notifications': 'No notifications',
    'my_child_attendance': 'My child attendance',
    'my_child': 'My Child',
    'status_completed': 'Completed',
    'status_scheduled': 'Scheduled',
    'status_overdue': 'Overdue',
    'fill_all_fields': 'Fill all fields',
    'vaccination_added': 'Vaccination added',
    'access_denied': 'Access denied',
    'teacher_no_access': 'Teachers cannot access this page',
    'my_child_vaccination': 'My child vaccination',
    'add_vaccination': 'Add Vaccination',
    'vaccination_list': 'Vaccination List',
    'next_dose': 'Next Dose',
    'new_vaccination': 'New Vaccination',
    'student': 'Student',
    'vaccine_name': 'Vaccine Name',
    'date': 'Date',
    'next_dose_date': 'Next Dose Date',
    'status': 'Status',
    'select': 'Select',
    'homework_added': 'Homework added',
    'my_child_homework': 'My child homework',
    'add_homework': 'Add Homework',
    'active_tasks': 'Active Tasks',
    'completed_tasks': 'Completed Tasks',
    'due_date': 'Due Date',
    'new_homework': 'New Homework',
    'group': 'Group',
    'title': 'Title',
    'description': 'Description',
    'sleep_record_added': 'Sleep record added',
    'my_child_sleep': 'My child sleep',
    'add_record': 'Add Record',
    'recorded_today': 'Recorded Today',
    'good_sleep': 'Good Sleep',
    'good_sleep_percentage': 'Good Sleep %',
    'sleep_records': 'Sleep Records',
    'new_sleep_record': 'New Sleep Record',
    'start_time': 'Start Time',
    'end_time': 'End Time',
    'quality': 'Quality',
    'good': 'Good',
    'fair': 'Fair',
    'poor': 'Poor',
    'activity_added': 'Activity added',
    'my_child_activities': 'My child activities',
    'add_activity': 'Add Activity',
    'no_activities_found': 'No activities found',
    'new_activity': 'New Activity',
    'activity_name': 'Activity Name',
    'type': 'Type',
    'time': 'Time',
    'duration': 'Duration',
    'minutes': 'minutes',
    'hours': 'hours',
    'active': 'Active',
    'completed': 'Completed',
    'overdue': 'Overdue',
    'leave_empty': 'Leave empty to keep current',
    'upload_photo': 'Upload Photo',
    'change_photo': 'Change Photo',
    'remove_photo': 'Remove Photo',
    'add_group': 'Add Group',
    'new_complaint': 'New Complaint',
    'subject': 'Subject',
    'subject_placeholder': 'Complaint subject...',
    'description_placeholder': 'Complaint description...',
    'send': 'Send',
    'super_dashboard': 'Super Dashboard',
    'crm_management': 'CRM Management',
    'add_student': 'Add Student',
    'add_teacher': 'Add Teacher',
    'add_parent': 'Add Parent',
    'add_meal': 'Add Meal',
    'add_complaint': 'Add Complaint',
    'edit_student': 'Edit Student',
    'edit_group': 'Edit Group',
    'edit_teacher': 'Edit Teacher',
    'edit_parent': 'Edit Parent',
    'today_menu': 'Today\'s Menu',
    'add_menu': 'Add Menu',
    'meal_breakfast': 'Breakfast',
    'meal_lunch': 'Lunch',
    'meal_snack': 'Snack',
    'meal_dinner': 'Dinner',
    'meal_not_set': 'Meal not set',
    'no_menu_set': 'No menu set for today',
    'menu_history': 'Menu History',
    'complaints_subtitle': 'Manage complaints and suggestions',
    'send_complaint': 'Send Complaint',
    'status_pending': 'Pending',
    'status_resolved': 'Resolved',
    'complaints_list': 'Complaints List',
    'complaint_title': 'Complaint Subject',
    'complaint_description': 'Complaint Description',
    'reply': "Reply",
    'response_placeholder': "Write your response...",
    'complaint_sent': "Complaint sent",
    'response_sent': "Response sent",
    'response': "Response",
    'student_info': "Student Information",
    'full_name': "Full Name",
    'age': "Age",
    'parent_info': "Parent Information",
    'parent_name': "Parent Name",
    'birth_date': "Birth Date",
    'photo_url': "Photo URL",
    'specialization': "Specialization",
    'assigned_groups': "Assigned Groups",
    'group_name': "Group Name",
    'age_range': "Age Range",
    'children': "Children",
    'child_count': "Child Count",
    'teachers_subtitle': "Teachers and their groups",
    'email_exists': "Email already exists",
    'password_min_length': "Password min 4 chars",
    'fill_required_fields': "Fill required fields",
    'select_branch_first': "Select branch first",
    'no_groups_in_branch': "No groups in this branch",
    'parent_not_found': "Parent not found",

    // Settings & Themes
    'theme_default': 'Default',
    'theme_default_desc': 'Classic blue & purple',
    'theme_ocean': 'Ocean',
    'theme_ocean_desc': 'Calm & refreshing',
    'theme_sunset': 'Sunset',
    'theme_sunset_desc': 'Warm & vibrant',
    'theme_forest': 'Forest',
    'theme_forest_desc': 'Natural & fresh',
    'theme_berry': 'Berry',
    'theme_berry_desc': 'Rich & playful',

    'settings_subtitle': 'Manage system settings',
    'select_language': 'Select system language',
    'select_theme_mode': 'Light or dark mode',
    'select_color_theme': 'Select color scheme',
    'preview_appearance': 'Appearance Preview',
    'danger_zone': 'Danger Zone',
    'manage_system_data': 'Manage system data',
    'reset_system': 'Reset System',
    'reset_system_desc': 'All entered data will be deleted and the system will return to its initial state.',
    'clear_data': 'Clear Data',
    'confirm_reset': 'Are you sure you want to delete all data? This action cannot be undone.',
    'system_reset_success': 'System reset',
    'button_primary': 'Primary',
    'button_secondary': 'Secondary',
    'button_success': 'Success',
    'button_warning': 'Warning',

    // QR Code
    'qr_code_subtitle': 'QR code scanning and attendance',
    'scan_simulator': 'Scanner Simulator',
    'click_to_simulate': 'Click the buttons below to record attendance',
    'check_in': 'Check In',
    'check_out': 'Check Out',
    'attendance_history': 'Attendance History',
    'scanned_in': 'In',
    'scanned_out': 'Out',
    'arrived': 'Arrived',
    'left': 'Left',
    'select_student_qr': 'Select Student',
    'download': 'Download',
    'refresh': 'Refresh',
    'check_in_success': 'Check-in recorded',
    'check_out_success': 'Check-out recorded',
    'select_student_error': 'Select a student first',

    // Dashboard
    'dashboard_subtitle': 'General information about kindergarten activity',

    // Users
    'users_subtitle': 'System Users',
    'add_user': 'Add User',
    'edit_user': 'Edit User',
    'new_user': 'New User',
    'filter_all': 'All',
    'filter_directors': 'Directors',
    'filter_admins': 'Admins',
    'filter_teachers': 'Teachers',
    'filter_parents': 'Parents',
    'role_director': 'Director',
    'role_admin': 'Admin',
    'role_teacher': 'Teacher',
    'role_parent': 'Parent',
    'role_superadmin': 'Super Admin',
    'fill_all_fields_error': 'Fill all fields',
    'branch_required_error': 'Branch selection is required for staff',
    'user_updated': 'User updated',
    'user_added': 'New user added',
    'user_deleted': 'User deleted',
    'delete_user_confirm': 'Are you sure you want to delete this user?',
    'no_permission': 'Access Denied',
    'no_permission_desc': 'You do not have permission to access this page',
    'full_name_label': 'Full Name',
    'new_password_placeholder': 'New password (to change)',
    'role': 'Role',
    'status_label': 'Status',
    'branch_select_hint': 'If a branch is selected, the user will only see data from that branch.',
    'no_users_found': 'No users found in this section',
    'delete_confirmation': "Are you sure you want to delete?",
    'create': "Create",
    'student_parent_created': "Student and Parent created",
    'fill_parent_info': "Fill parent info",
    'new_group': "New Group",
    'group_updated': "Group updated",
    'group_deleted': "Group deleted",
    'group_added': "Group added",
    'student_updated': "Student updated",
    'student_deleted': "Student deleted",
    'teacher_updated': "Teacher updated",
    'teacher_deleted': "Teacher deleted",
    'parent_updated': "Parent updated",
    'parent_deleted': "Parent deleted",
    'parent_added': "Parent added",
    'teacher_created': "Teacher created",
    'all_groups': "All Groups",
    'email_login': "Email (Login)",
    'add_student_parent': "New Student and Parent",
    'financial_records': 'Financial Reports',
    'annual_stats': "Annual Statistics",
    'recent_transactions': "Recent Transactions",
    'financial_record': "Financial Record",
    'amount': "Amount",
    'amount_sum': "Amount (sum)",
    'category': "Category",
    'income_added': "Income Added",
    'expense_added': "Expense Added",
    'product_name': "Product Name",
    'quantity': "Quantity",
    'unit': "Unit",
    'min_stock': "Min. Stock",
    'total_products': "Total Products",
    'categories': "Categories",
    'low_stock': "Low Stock",
    'low_stock_items': "Low Stock Items",
    'product_added': "Product Added",
    'add_product': "Add Product",
    'record_updated': "Record updated",
    'record_deleted': "Record deleted",
    'edit_record': "Edit Record",
    'delete_record': "Delete Record",
    'new_product': "New Product",
    'updated': "Updated",
    'warehouse_management': "Warehouse Management",
    'no_active_tasks': "No Active Tasks",
    'branch_not_found': "Branch Not Found",
    'branch_added': "New Branch Added",
    'branch_updated': "Branch Updated",
    'branch_deleted': "Branch Deleted",
    'admission_applications': "Admission Applications",
    'add_application': "Add Application",
    'pending': "Pending",
    'approved': "Approved",
    'rejected': "Rejected",
    'waitlist': "Waitlist",
    'total_applications': "Total Applications",
    'applications_list': "Applications List",

    'preferred_branch': "Preferred Branch",
    'application_added': "Application Added",
    'status_updated': "Status Updated",
    'approve': "Approve",
    'reject': "Reject",
    'activities_schedule': "Activities Schedule",
    'educational': "Educational",
    'physical': "Physical",
    'creative': "Creative",
    'social': "Social",
    'child_name': "Child Name",

    'duration_min': "Duration (min)",
    'about_activity': "About activity...",
    'sleep_monitoring': "Sleep Monitoring",
    'new_menu': "New Menu",
    'menu_name': "Menu Name",
    'meal_type': "Meal Time",
    'calories': "Calories",
    'menu_items': "Menu Items",
    'my_groups': "My Groups",
    'my_children': "My Children",
  },
};


const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const { users, addUser } = useData();

  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'uz';
  });

  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = localStorage.getItem('theme');
    return (saved as Theme) || 'light';
  });

  const [colorTheme, setColorThemeState] = useState<ColorTheme>(() => {
    const saved = localStorage.getItem('colorTheme');
    return (saved as ColorTheme) || 'default';
  });

  const [user, setUserState] = useState<User | null>(() => {
    const saved = localStorage.getItem('user');
    return saved ? JSON.parse(saved) : null;
  });

  const [currentBranch, setCurrentBranchState] = useState<string>(() => {
    const saved = localStorage.getItem('currentBranch');
    return saved || 'all';
  });

  // Strict Branch Logic: When user changes (login), enforce their branch
  useEffect(() => {
    if (user?.branchId) {
      setCurrentBranchState(user.branchId);
      localStorage.setItem('currentBranch', user.branchId);
    }
  }, [user]);

  const setCurrentBranch = (id: string) => {
    setCurrentBranchState(id);
    localStorage.setItem('currentBranch', id);
  };

  // Default Users Creation
  useEffect(() => {
    // Check if we need to seed any demo users
    const demoUsers: User[] = [
      {
        id: 'director-demo',
        name: 'Director',
        email: 'director@kindergarten.uz',
        role: 'director',
        status: 'active',
        createdAt: new Date().toISOString().split('T')[0],
        password: '1234'
      },
      {
        id: 'admin-demo',
        name: 'Admin',
        email: 'admin@kindergarten.uz',
        role: 'admin',
        status: 'active',
        createdAt: new Date().toISOString().split('T')[0],
        password: '1234'
      },
      {
        id: 'teacher-demo',
        name: 'Teacher',
        email: 'teacher@kindergarten.uz',
        role: 'teacher',
        status: 'active',
        createdAt: new Date().toISOString().split('T')[0],
        password: '1234'
      },
      {
        id: 'parent-demo',
        name: 'Parent',
        email: 'parent@kindergarten.uz',
        role: 'parent',
        status: 'active',
        createdAt: new Date().toISOString().split('T')[0],
        password: '1234'
      }
    ];

    let hasChanges = false;
    demoUsers.forEach(demoUser => {
      // Check if user exists by email
      if (!users.some(u => u.email.toLowerCase() === demoUser.email.toLowerCase())) {
        try {
          addUser(demoUser);
          hasChanges = true;
        } catch (e) {
          console.error(`Failed to create demo user ${demoUser.name}`, e);
        }
      }
    });

    if (hasChanges) {
      console.log("Missing demo users created");
    }
  }, [users, addUser]);


  // User-specific Settings Logic
  useEffect(() => {
    if (user?.id) {
      // Load user-specific settings on login
      const savedTheme = localStorage.getItem(`theme_${user.id}`) as Theme;
      const savedColor = localStorage.getItem(`colorTheme_${user.id}`) as ColorTheme;

      setThemeState(savedTheme || 'light');
      setColorThemeState(savedColor || 'default');
    } else {
      // Revert to global/default settings on logout
      const globalTheme = localStorage.getItem('theme') as Theme;
      const globalColor = localStorage.getItem('colorTheme') as ColorTheme;

      setThemeState(globalTheme || 'light');
      setColorThemeState(globalColor || 'default');
    }
  }, [user]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
    if (user?.id) {
      localStorage.setItem(`theme_${user.id}`, newTheme);
    } else {
      localStorage.setItem('theme', newTheme);
    }
  };

  const setColorTheme = (newColorTheme: ColorTheme) => {
    setColorThemeState(newColorTheme);
    if (user?.id) {
      localStorage.setItem(`colorTheme_${user.id}`, newColorTheme);
    } else {
      localStorage.setItem('colorTheme', newColorTheme);
    }
  };

  const setUser = (newUser: User | null) => {
    setUserState(newUser);
    if (newUser) {
      localStorage.setItem('user', JSON.stringify(newUser));
    } else {
      localStorage.removeItem('user');
    }
  };

  const login = async (email: string, password: string): Promise<boolean> => {
    await new Promise(resolve => setTimeout(resolve, 1000));

    const foundUser = users.find(u => u.email.toLowerCase() === email.toLowerCase());

    if (foundUser) {
      // If user has a password, check it
      if (foundUser.password) {
        if (foundUser.password === password) {
          setUser(foundUser);
          return true;
        }
      } else {
        // Fallback for old users without password (allow any password > 3 chars or just strict '1234')
        // For security, let's enforce '1234' as default for legacy users or just allow if length > 3 like before
        if (password.length >= 4) {
          setUser(foundUser);
          return true;
        }
      }
    }
    return false;
  };

  const logout = () => {
    setUser(null);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove('theme-ocean', 'theme-sunset', 'theme-forest', 'theme-berry');
    if (colorTheme !== 'default') {
      root.classList.add(`theme-${colorTheme}`);
    }
  }, [colorTheme]);

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        theme,
        setTheme,
        colorTheme,
        setColorTheme,
        user,
        setUser,
        isAuthenticated: !!user,
        login,
        logout,
        t,
        currentBranch,
        setCurrentBranch,
      }}
    >
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
};
